# Data set parameters

DEF_ROOT = "/disk12/legacy/"
DEF_SIM_NAMES = ["GVD_C700_l1600n2048_SLEGAC"]

# Sampling parameters

DEF_NUM_SPHERE_SAMPLES = 1000
DEF_NUM_HIST_BINS = 1000
DEF_NUM_OD_HIST_BINS = 1000

DEF_REDSHIFTS = [0, 1, 2, 6, 10]
DEF_RADII = [10, 20, 50, 100]

# Caching access defaults:
DEF_USE_TOTAL_MASSES_CACHE = True
DEF_USE_MASSES_CACHE = True
DEF_USE_OVERDENSITIES_CACHE = True
DEF_USE_RHO_BAR_CACHE = True
DEF_USE_STD_DEV_CACHE = True
DEF_USE_PS_CACHE = True
