%YAML 1.2
---
sampling: 
 num_sp_samples: 1000
radii: 
 - 10
redshifts: 
 - 5
sim_data: 
 root: /disk12/legacy/
 simulation_names:
 - GVD_C700_l10n1024_SLEGAC
caches: !include ../defaults/radii_cache.yaml

