%YAML 1.2
---
sampling: 
 num_sp_samples: 1000
radii: 
 - 20
redshifts: 
 - 5
sim_data: 
 root: /disk12/legacy/
 simulation_names:
 - GVD_C900_l100n2048_SLEGAC
caches: !include ../defaults/radii_cache.yaml

