%YAML 1.2
---
sampling: 
 num_sp_samples: 1000
radii: 
 - 20
redshifts: 
 - 0
sim_data: 
 root: /disk12/legacy/
 simulation_names:
 - GVD_C700_l1600n64_SLEGAC
caches: !include ../defaults/radii_cache.yaml

