%YAML 1.2
---
sampling: 
 num_sp_samples: 1000
radii: 
 - 50
redshifts: 
 - 3
sim_data: 
 root: /disk12/legacy/
 simulation_names:
 - GVD_C700_l100n256_SLEGAC
caches: !include ../defaults/radii_cache.yaml

