dirs:
  root: ../plots/
  mass_function: mass_function/{0}/
  overdensity: deltas/{0}/
  press_schechter: press_schechter/{0}/
  total: total_mass_function/{0}/
  compared: compared/{0}/
pattern:
  mass_function: mass_function_r{1:.2f}_z{2:.2f}.png
  overdensity: overdensity_r{1:.2f}_z{2:.2f}.png
  press_schechter: press_schechter_z{1:.2f}.png
  total: total_mass_function_z{1:.2f}.png
  compared: comparison_ps_mass_function_r{1:.2f}_z{2:.2f}.png