%YAML 1.2
---
radii:
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
redshifts:
- 0.0
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
- 1
- 2
- 4
- 6
- 8
- 10
- 20
- 99
datatypes:
  groups: true
  halos_h5: true
  rockstar: true
  snapshots: false
tasks:
  mass_function: false
  overdensity: true
  rho_bar: false
  std_dev: false
  total_mass_function: false