%YAML 1.2
---
radii:
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
redshifts:
- 0.0
- 0.25
- 0.5
- 1
- 2
- 4
- 6
- 8
- 10
- 15
- 20
- 99
datatypes:
  groups: false
  halos_h5: false
  rockstar: false
  snapshots: true
tasks:
  mass_function: false
  overdensity: true
  rho_bar: false
  std_dev: false
  total_mass_function: false