%YAML 1.2
---
datatypes:
  groups: false
  halos_h5: true
  rockstar: false
  snapshots: true
tasks:
  mass_function: false
  overdensity: true
  rho_bar: false
  std_dev: false
  total_mass_function: false
caches:
  use_fits_cache: false
  use_standard_deviation_cache: false