%YAML 1.2
---
number_of_histogram_bins: 1000
number_of_overdensity_histogram_bins: 1000
number_of_sphere_samples: 10000
radii:
- 10
- 20
- 50
- 100
- 200
- 300
redshifts:
- 0
- 1
- 2
- 6
- 10
root: /disk12/legacy
simulation_names:
- GVD_C700_l1600n2048_SLEGAC
