%YAML 1.2
---
radii:
- 10
- 20
- 50
- 100
- 200
- 300
redshifts:
- 0
- 1
- 2
- 6
- 10
caches:
  use_masses_cache: false
  use_overdensities_cache: false
  use_rho_bar_cache: false
  use_standard_deviation_cache: false
  use_total_cache: false
  use_press_schechter_cache: false
