%YAML 1.2
---
number_of_histogram_bins: 100
number_of_overdensity_histogram_bins: 100
number_of_sphere_samples: 1000
radii:
- 100
redshifts:
- 0
root: /disk12/legacy
simulation_names:
- GVD_C700_l1600n2048_SLEGAC
use_masses_cache: true
use_overdensities_cache: true
use_rho_bar_cache: true
use_standard_deviation_cache: true
use_total_cache: true
use_press_schechter_cache: true
