%YAML 1.2
---
number_of_histogram_bins: 1000
number_of_overdensity_histogram_bins: 1000
number_of_sphere_samples: 1000
radii:
- 10
redshifts:
- 0
root: /disk12/legacy
simulation_name: GVD_C700_l1600n2048_SLEGAC

use_total_cache: False
use_masses_cache: True
use_overdensities_cache: True
