%YAML 1.2
---
radii:
- 20
- 100
redshifts:
- 0
- 8
caches:
  use_masses_cache: false
  use_overdensities_cache: true
  use_rho_bar_cache: true
  use_standard_deviation_cache: true
  use_total_cache: true
