%YAML 1.2
---
datatypes: !include defaults/radii_datatypes.yaml
radii: 
- 10

redshifts: 
- 0.0
- 0.25
- 0.5
- 1
- 2
- 4
- 6
- 8
- 10
- 15
- 20
- 99

sim_data: 
 root: /disk12/legacy/
 simulation_names:
 - GVD_C700_l1600n2048_SLEGAC


