%YAML 1.2
---
datatypes: !include defaults/radii_datatypes.yaml
radii: 
- 1
- 2
- 3
- 4
- 5
- 10
- 15
- 20
- 25
- 30
- 35
- 40
- 45
- 50
- 55
- 60
- 70
- 80
- 90
- 100
redshifts: 
- 0.0
- 0.25
- 0.5
- 1
- 2
- 4
- 6
- 8
- 10
- 15
- 20
- 99
caches:
  use_standard_deviation_cache: false
datatypes:
  groups: false
  halos_h5: false
  rockstar: false
  snapshots: true
