%YAML 1.2
---
datatypes: !include defaults/radii_datatypes.yaml
radii: 
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
redshifts: 
- 0.0
- 0.25
- 0.5
- 1
- 2
- 4
- 6
- 8
- 10
- 15
- 20
- 99
caches:
  use_standard_deviation_cache: false
