%YAML 1.2
---
sampling:
  num_hist_bins: 100
  num_od_hist_bins: 100
  num_sp_samples: 1000
radii:
- 123
redshifts:
- 0
caches:
  use_masses_cache: false
  use_overdensities_cache: false
  use_rho_bar_cache: false
  use_standard_deviation_cache: false
  use_total_cache: true
  use_press_schechter_cache: true
  use_sphere_samples: true
datatypes:
  groups: false
  halos_h5: true
  rockstar: false
  snapshots: false
