%YAML 1.2
---
sampling:
  overdensity_std_dev_tol: !!float 1e-2
  converge_std_dev: false
  sphere_sample_iteration: 500
  sphere_sample_hotsave: false
  num_sp_samples: 1000
radii:
- 123
redshifts:
- 0
caches:
  use_masses_cache: true
  use_overdensities_cache: false
  use_rho_bar_cache: true
  use_standard_deviation_cache: true
  use_total_cache: true
  use_press_schechter_cache: true
  use_sphere_samples: true
datatypes:
  groups: false
  halos_h5: false
  rockstar: false
  snapshots: true
tasks:
  mass_function: false
  overdensity: true
  rho_bar: false
  std_dev: false
  total_mass_function: false
plotting:
    dirs:
      root: ../plots/testing/